export const GET_ALL_AIRLINES = "GET_ALL_AIRLINES";
export const GET_ALL_FLIGHTS = "GET_ALL_FLIGHTS";
export const ADD_FLIGHT = "ADD_FLIGHT";
export const POPULATE_PRE_EDIT_FLIGHT = "POPULATE_PRE_EDIT_FLIGHT";
export const PRE_EDIT_FLIGHT = "PRE_EDIT_FLIGHT";
export const EDIT_FLIGHT = "EDIT_FLIGHT";
export const DELETE_FLIGHT = "DELETE_FLIGHT";
export const CHANGE_FLIGHT_MODE = "CHANGE_FLIGHT_MODE";